language: java

before_script:
  - wget -c http://download.libsodium.org/libsodium/releases/libsodium-0.6.1.tar.gz
  - tar xzvf libsodium-0.6.1.tar.gz
  - cd libsodium-0.6.1 && mkdir vendor
  - ./configure --prefix=`pwd`/vendor
  - make && make install
  - cd ../

script:
  - export LD_LIBRARY_PATH="/home/travis/build/abstractj/kalium/libsodium-0.6.1/vendor/lib"
  - mvn clean install

env: JAVA_OPTS="-Djava.library.path=/home/travis/build/abstractj/kalium/libsodium-0.6.1/vendor/lib"

jdk:
  - oraclejdk7
  - openjdk6

after_success:
  - rm -rf libsodium-0.6.1*
